In [23]:
import pandas as pd 
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pickle

In [24]:
# add csv file 
data = pd.read_csv('Churn_Modelling.csv')

data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [25]:
# remove or drop unnecessary columns

data = data.drop(['RowNumber', 'CustomerId', 'Surname', 'Gender', 'Exited'], axis=1)

data.head()

,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,42,2,0.00,1,1,1,101348.88
1,608,Spain,41,1,83807.86,1,0,1,112542.58
2,502,France,42,8,159660.80,3,1,0,113931.57
3,699,France,39,1,0.00,2,0,0,93826.63
4,850,Spain,43,2,125510.82,1,1,1,79084.10

In [26]:
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [27]:
onehot_encoder_geo.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [28]:
geo_encoder_df = pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [29]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoder_df], axis=1)
data.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0

In [30]:
with open ('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [31]:
data.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0

In [32]:
# Divide data into the dependent and independent features

X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

# split the data into thetraining  and testing sets

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# scale these features

# Scale input features
scaler_x = StandardScaler()
X_train_scaled = scaler_x.fit_transform(X_train)
X_test_scaled = scaler_x.transform(X_test)

# Scale target (y)
scaler_y = StandardScaler()
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1))
y_test_scaled = scaler_y.transform(y_test.values.reshape(-1, 1)) 


# # 7. Linear Regression Model
# model = LinearRegression()
# model.fit(X_train, y_train)
# y_pred = model.predict(X_test)

In [33]:
X_train_scaled

array([[ 0.35649971, -0.6557859 ,  0.34567966, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.29493847, -0.3483691 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213, -1.41636539, -0.69539349, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -0.08535128, -1.38944225, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.3900109 ,  1.03972843, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  1.15059039, -1.38944225, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [34]:
X_test_scaled

array([[-0.57749609, -0.6557859 , -0.69539349, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.3900109 , -1.38944225, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743,  0.48508334, -0.3483691 , ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987,  0.77030065,  0.69270405, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609, -0.94100321, -0.3483691 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.00972116, -1.38944225, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [35]:
y_test_scaled

array([[-1.01960511],
       [ 0.79888291],
       [-0.72797953],
       ...,
       [-1.16591585],
       [-0.41163463],
       [ 0.12593183]])

In [36]:
#  save the scaler file 

with open ('scaler_X.pkl', 'wb') as file:
    pickle.dump(scaler_x, file)


with open ('scaler_y.pkl', 'wb') as file:
    pickle.dump(scaler_y, file)

In [37]:
import tensorflow as tf  
from tensorflow.keras.models import Sequential  # type: ignore
from tensorflow.keras.layers import Dense     # type: ignore
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard # type: ignore
from sklearn.metrics import mean_absolute_error, r2_score 

import datetime

In [38]:
(X_test.shape[1],)

(10,)

In [39]:
# build our salary prediction ANN model 
model = Sequential([
    Dense(512,activation='relu', input_shape=(X_train.shape[1],)),
    Dense(256,activation='relu'),
    Dense(128,activation='relu'),
    Dense(64,activation='relu'),
    Dense(32,activation='relu'),
    Dense(1,activation='linear')
])

In [40]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 512)               5632

 dense_6 (Dense)             (None, 256)               131328

 dense_7 (Dense)             (None, 128)               32896

 dense_8 (Dense)             (None, 64)                8256

 dense_9 (Dense)             (None, 32)                2080

 dense_10 (Dense)            (None, 1)                 33

=================================================================
Total params: 180225 (704.00 KB)
Trainable params: 180225 (704.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [41]:
# Optimizing model
import tensorflow

opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [42]:
# compile the model

model.compile(optimizer='adam',loss='mean_absolute_error',)

In [43]:
# train the model {early stopping method}

early_stop = EarlyStopping(monitor='val_loss', patience=100)

history = model.fit (
    X_train_scaled,y_train_scaled,validation_data=(X_test_scaled,y_test_scaled),epochs=100,batch_size = 32, callbacks=[early_stop]
)

Epoch 1/100
250/250 [==============================] - 7s 10ms/step - loss: 0.8672 - val_loss: 0.8665
Epoch 2/100
250/250 [==============================] - 2s 8ms/step - loss: 0.8644 - val_loss: 0.8661
Epoch 3/100
250/250 [==============================] - 3s 10ms/step - loss: 0.8644 - val_loss: 0.8685
Epoch 4/100
250/250 [==============================] - 2s 8ms/step - loss: 0.8635 - val_loss: 0.8667
Epoch 5/100
250/250 [==============================] - 2s 7ms/step - loss: 0.8630 - val_loss: 0.8697
Epoch 6/100
250/250 [==============================] - 2s 8ms/step - loss: 0.8630 - val_loss: 0.8708
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 0.8638 - val_loss: 0.8673
Epoch 8/100
250/250 [==============================] - 1s 6ms/step - loss: 0.8626 - val_loss: 0.8689
Epoch 9/100
250/250 [==============================] - 1s 6ms/step - loss: 0.8623 - val_loss: 0.8679
Epoch 10/100
250/250 [==============================] - 2s 6ms/step - loss: 0.8610 - val_loss: 0.8701
Epoch 11/100
250/250 [==============================] - 2s 8ms/step - loss: 0.8616 - val_loss: 0.8691
Epoch 12/100
250/250 [==============================] - 2s 10ms/step - loss: 0.8592 - val_loss: 0.8704
Epoch 13/100
250/250 [==============================] - 2s 8ms/step - loss: 0.8597 - val_loss: 0.8703
Epoch 14/100
250/250 [==============================] - 2s 7ms/step - loss: 0.8591 - val_loss: 0.8725
Epoch 15/100
250/250 [==============================] - 2s 7ms/step - loss: 0.8567 - val_loss: 0.8684
Epoch 16/100
250/250 [==============================] - 2s 7ms/step - loss: 0.8563 - val_loss: 0.8728
Epoch 17/100
250/250 [==============================] - 2s 6ms/step - loss: 0.8527 - val_loss: 0.8862
Epoch 18/100
250/250 [==============================] - 2s 6ms/step - loss: 0.8502 - val_loss: 0.8738
Epoch 19/100
250/250 [==============================] - 2s 6ms/step - loss: 0.8493 - val_loss: 0.8746
Epoch 20/100
250/250 [==============================] - 1s 6ms/step - loss: 0.8476 - val_loss: 0.8825
Epoch 21/100
250/250 [==============================] - 2s 6ms/step - loss: 0.8450 - val_loss: 0.8897
Epoch 22/100
250/250 [==============================] - 2s 6ms/step - loss: 0.8435 - val_loss: 0.8934
Epoch 23/100
250/250 [==============================] - 2s 6ms/step - loss: 0.8380 - val_loss: 0.8993
Epoch 24/100
250/250 [==============================] - 2s 6ms/step - loss: 0.8351 - val_loss: 0.9029
Epoch 25/100
250/250 [==============================] - 2s 6ms/step - loss: 0.8327 - val_loss: 0.9145
Epoch 26/100
250/250 [==============================] - 2s 6ms/step - loss: 0.8297 - val_loss: 0.8942
Epoch 27/100
250/250 [==============================] - 2s 6ms/step - loss: 0.8243 - val_loss: 0.8914
Epoch 28/100
250/250 [==============================] - 1s 6ms/step - loss: 0.8202 - val_loss: 0.9010
Epoch 29/100
250/250 [==============================] - 2s 7ms/step - loss: 0.8166 - val_loss: 0.8979
Epoch 30/100
250/250 [==============================] - 2s 7ms/step - loss: 0.8096 - val_loss: 0.9153
Epoch 31/100
250/250 [==============================] - 2s 7ms/step - loss: 0.8054 - val_loss: 0.9058
Epoch 32/100
250/250 [==============================] - 2s 7ms/step - loss: 0.8001 - val_loss: 0.9092
Epoch 33/100
250/250 [==============================] - 2s 7ms/step - loss: 0.7968 - val_loss: 0.9208
Epoch 34/100
250/250 [==============================] - 2s 6ms/step - loss: 0.7885 - val_loss: 0.9318
Epoch 35/100
250/250 [==============================] - 2s 6ms/step - loss: 0.7805 - val_loss: 0.9412
Epoch 36/100
250/250 [==============================] - 2s 6ms/step - loss: 0.7766 - val_loss: 0.9315
Epoch 37/100
250/250 [==============================] - 2s 6ms/step - loss: 0.7663 - val_loss: 0.9276
Epoch 38/100
250/250 [==============================] - 2s 6ms/step - loss: 0.7611 - val_loss: 0.9395
Epoch 39/100
250/250 [==============================] - 2s 6ms/step - loss: 0.7539 - val_loss: 0.9285
Epoch 40/100
250/250 [==============================] - 2s 6ms/step - loss: 0.7446 - val_loss: 0.9465
Epoch 41/100
250/250 [==============================] - 2s 6ms/step - loss: 0.7380 - val_loss: 0.9474
Epoch 42/100
250/250 [==============================] - 2s 7ms/step - loss: 0.7323 - val_loss: 0.9495
Epoch 43/100
250/250 [==============================] - 2s 6ms/step - loss: 0.7254 - val_loss: 0.9495
Epoch 44/100
250/250 [==============================] - 2s 6ms/step - loss: 0.7141 - val_loss: 0.9681
Epoch 45/100
250/250 [==============================] - 1s 6ms/step - loss: 0.7051 - val_loss: 0.9614
Epoch 46/100
250/250 [==============================] - 2s 6ms/step - loss: 0.6932 - val_loss: 0.9620
Epoch 47/100
250/250 [==============================] - 2s 6ms/step - loss: 0.6910 - val_loss: 0.9801
Epoch 48/100
250/250 [==============================] - 2s 7ms/step - loss: 0.6803 - val_loss: 0.9735
Epoch 49/100
250/250 [==============================] - 2s 7ms/step - loss: 0.6734 - val_loss: 0.9905
Epoch 50/100
250/250 [==============================] - 2s 8ms/step - loss: 0.6656 - val_loss: 0.9824
Epoch 51/100
250/250 [==============================] - 2s 7ms/step - loss: 0.6564 - val_loss: 0.9695
Epoch 52/100
250/250 [==============================] - 2s 7ms/step - loss: 0.6488 - val_loss: 0.9712
Epoch 53/100
250/250 [==============================] - 2s 6ms/step - loss: 0.6415 - val_loss: 0.9986
Epoch 54/100
250/250 [==============================] - 2s 6ms/step - loss: 0.6374 - val_loss: 1.0071
Epoch 55/100
250/250 [==============================] - 2s 6ms/step - loss: 0.6266 - val_loss: 1.0083
Epoch 56/100
250/250 [==============================] - 2s 6ms/step - loss: 0.6180 - val_loss: 1.0200
Epoch 57/100
250/250 [==============================] - 2s 6ms/step - loss: 0.6144 - val_loss: 1.0084
Epoch 58/100
250/250 [==============================] - 2s 6ms/step - loss: 0.6010 - val_loss: 1.0278
Epoch 59/100
250/250 [==============================] - 2s 6ms/step - loss: 0.6013 - val_loss: 1.0119
Epoch 60/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5908 - val_loss: 0.9964
Epoch 61/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5835 - val_loss: 1.0085
Epoch 62/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5803 - val_loss: 1.0196
Epoch 63/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5704 - val_loss: 1.0287
Epoch 64/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5639 - val_loss: 1.0254
Epoch 65/100
250/250 [==============================] - 2s 7ms/step - loss: 0.5571 - val_loss: 1.0089
Epoch 66/100
250/250 [==============================] - 2s 7ms/step - loss: 0.5609 - val_loss: 1.0238
Epoch 67/100
250/250 [==============================] - 2s 7ms/step - loss: 0.5539 - val_loss: 1.0240
Epoch 68/100
250/250 [==============================] - 2s 7ms/step - loss: 0.5397 - val_loss: 1.0309
Epoch 69/100
250/250 [==============================] - 2s 8ms/step - loss: 0.5418 - val_loss: 1.0427
Epoch 70/100
250/250 [==============================] - 2s 8ms/step - loss: 0.5292 - val_loss: 1.0385
Epoch 71/100
250/250 [==============================] - 2s 7ms/step - loss: 0.5272 - val_loss: 1.0437
Epoch 72/100
250/250 [==============================] - 2s 7ms/step - loss: 0.5213 - val_loss: 1.0236
Epoch 73/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5184 - val_loss: 1.0427
Epoch 74/100
250/250 [==============================] - 2s 7ms/step - loss: 0.5088 - val_loss: 1.0406
Epoch 75/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5090 - val_loss: 1.0492
Epoch 76/100
250/250 [==============================] - 2s 7ms/step - loss: 0.5015 - val_loss: 1.0336
Epoch 77/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4939 - val_loss: 1.0510
Epoch 78/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4908 - val_loss: 1.0424
Epoch 79/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4929 - val_loss: 1.0265
Epoch 80/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4840 - val_loss: 1.0445
Epoch 81/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4816 - val_loss: 1.0467
Epoch 82/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4739 - val_loss: 1.0569
Epoch 83/100
250/250 [==============================] - 2s 9ms/step - loss: 0.4762 - val_loss: 1.0584
Epoch 84/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4704 - val_loss: 1.0580
Epoch 85/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4608 - val_loss: 1.0478
Epoch 86/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4599 - val_loss: 1.0523
Epoch 87/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4587 - val_loss: 1.0583
Epoch 88/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4595 - val_loss: 1.0458
Epoch 89/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4527 - val_loss: 1.0571
Epoch 90/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4460 - val_loss: 1.0534
Epoch 91/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4489 - val_loss: 1.0754
Epoch 92/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4440 - val_loss: 1.0574
Epoch 93/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4393 - val_loss: 1.0474
Epoch 94/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4338 - val_loss: 1.0797
Epoch 95/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4347 - val_loss: 1.0582
Epoch 96/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4306 - val_loss: 1.0731
Epoch 97/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4258 - val_loss: 1.0511
Epoch 98/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4246 - val_loss: 1.0588
Epoch 99/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4159 - val_loss: 1.0626
Epoch 100/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4167 - val_loss: 1.0760

In [44]:
model.save('model.h5')

c:\Users\dell\OneDrive\Desktop\Advance projects\salary prediction ANN model\salary\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(